#!/usr/bin/env python3
"""
inline_visuals.py — replace <!-- VISUAL:name --> placeholders in wiki HTML
with the inline SVG generated by gen_visuals.py.

Run gen_visuals.py first. Usage:
    python3 wiki/scripts/inline_visuals.py
"""
import json
import os
import re

WIKI = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VISUALS = json.load(open(os.path.join(WIKI, "assets", "visuals.json"), encoding="utf-8"))

PLACEHOLDER = re.compile(r"<!--\s*VISUAL:([a-z0-9_]+)\s*-->")


def main():
    total = 0
    for root, dirs, files in os.walk(WIKI):
        dirs[:] = [d for d in dirs if d not in ("scripts", "assets", "css", "js")]
        for f in files:
            if not f.endswith(".html"):
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, WIKI)
            html = open(full, encoding="utf-8").read()

            def sub(m):
                name = m.group(1)
                if name not in VISUALS:
                    raise SystemExit(f"unknown visual '{name}' in {rel}")
                return '<div class="blueprint-body">\n' + VISUALS[name] + '\n</div>'

            new = PLACEHOLDER.sub(sub, html)
            # refresh already-embedded SVGs, matched by their unique aria-label
            for name, svg in VISUALS.items():
                m = re.search(r'aria-label="([^"]+)"', svg)
                if not m:
                    continue
                label = re.escape(m.group(1))
                pat = re.compile(r'<div class="blueprint-body">\s*<svg[^>]*aria-label="' + label + r'"[\s\S]*?</svg>\s*</div>')
                if pat.search(new):
                    new = pat.sub(lambda _m: '<div class="blueprint-body">\n' + svg + '\n</div>', new)
            if new != html:
                open(full, "w", encoding="utf-8").write(new)
                n = len(PLACEHOLDER.findall(html))
                print(f"inlined {n} visual(s) into {rel}")
                total += n
    print(f"done — {total} visual(s) inlined")


if __name__ == "__main__":
    main()
